### ISSUE TITLE
请问这个TransactionalConfig类里如何配置事物的切点

### ISSUE THREAD

**Issue by yangkebiao** [yujunhao8831/spring-boot-start-current#2]
spring-boot-start-current/aidijing-basic-config/src/main/java/com/aidijing/config/TransactionalConfig.java
我想配置事务的切点，类似于xml里的这种
<aop:config  proxy-target-class="true">
		<aop:advisor pointcut="execution(* com.demo.service..*.*(..))" advice-ref="transactionAdvice" />  
	</aop:config>
目前使用这个配置类TransactionalConfig，访问任何一个service会出现java.sql.SQLException: Connection is closed异常。会不会是因为TransactionalConfig里没有配置事务的切点导致的。希望作者能给解答一下，谢谢

**Comment by yujunhao8831** [comment]
不太明白你的意思.
TransactionalConfig 这里面已经配置了切点,只不过切点是以beanName的形式

``` java
// 默认的切点就是这里
private static final String[] DEFAULT_TRANSACTION_BEAN_NAMES                       = { "*Service" , "*ServiceImpl" };

```

**Comment by yangkebiao** [comment]
好吧，可能只能这么匹配吧。
但访问还是有问题。
这是demo的地址，https://gitee.com/yangkb/springboot-beetl-beetlsql
项目启动后，访问http://127.0.0.1:9090/user/info?id=1，会超出异常：
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:490)
	at com.sun.proxy.$Proxy70.getMetaData(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.getMetaData(ProxyConnection.java:361)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getMetaData(HikariProxyConnection.java)
	at org.beetl.sql.core.db.MetadataManager.initTable(MetadataManager.java:127)
	... 70 common frames omitted
但如果项目启动后访问http://127.0.0.1:9090/user/batchAdd?name=test（这个接口里我故意抛了一个异常，测试回滚），再访问http://127.0.0.1:9090/user/info?id=1，它又没问题了，好奇怪

**Comment by yujunhao8831** [comment]
+ pointcut 切点是可以配置不同形式的,只是我配置的是以beanName的形式,你想配置成按包切的形式,也是可以的,要自己去修改. 或者直接引入xml, spring boot也是支持的 @ImportResouce
+ 至于报的sql异常,那我就不清楚了, beetlsql 我是没使用过的. 说到底还是配置不正确的问题

**Comment by yangkebiao** [comment]
好的，谢谢你！
